// ====================================
// Results Section Component
// ====================================
// This displays all the calculation results after the user clicks Calculate
// Shows 4 result cards and a monthly chart

import React from 'react';
import ResultCard from './ResultCard';
import MonthlyChart from './MonthlyChart';

function ResultsSection({ results, solarData, formData, isVisible }) {
    // Don't show anything if there are no results yet
    if (!isVisible || !results) return null;

    return (
        <section className="results-section">
            <h2 className="section-title">Solar Potential Results</h2>

            {/* Grid of 4 result cards */}
            <div className="results-grid">

                {/* Card 1: Annual Energy Generation */}
                <ResultCard
                    icon="⚡"
                    title="Annual Energy Generation"
                    value={results.annualEnergy}
                    unit="kWh/year"
                    description="Estimated electricity generated by your solar panels"
                    colorClass="energy-card"
                />

                {/* Card 2: Annual Cost Savings */}
                <ResultCard
                    icon="💰"
                    title="Annual Cost Savings"
                    value={results.annualSavings}
                    unit="/year"
                    currency="₹"
                    description="Estimated savings on your electricity bill"
                    colorClass="savings-card"
                />

                {/* Card 3: CO₂ Emission Reduction */}
                <ResultCard
                    icon="🌱"
                    title="CO₂ Emission Reduction"
                    value={results.co2Saved}
                    unit="kg/year"
                    description="Your contribution to reducing carbon emissions"
                    colorClass="co2-card"
                />

                {/* Card 4: Average Solar Irradiance */}
                <ResultCard
                    icon="☀️"
                    title="Average Solar Irradiance"
                    value={parseFloat(results.avgDailyIrradiance.toFixed(2))}
                    unit="kWh/m²/day"
                    description="Daily solar energy received at your location"
                    colorClass="irradiance-card"
                />
            </div>

            {/* Monthly Energy Chart */}
            <MonthlyChart
                monthlyData={solarData?.data?.monthlyData}
                roofArea={parseFloat(formData.roofArea)}
                efficiency={parseFloat(formData.panelEfficiency)}
                annualEnergy={results.annualEnergy}
            />

            {/* Data Source Information */}
            <div className="data-note">
                <p>
                    <strong>Data Source:</strong> Solar irradiance data from{' '}
                    <a href="https://power.larc.nasa.gov/" target="_blank" rel="noopener noreferrer">
                        NASA POWER API
                    </a>
                    {' '}(All Sky Surface Shortwave Downward Irradiance)
                </p>
                <p className="disclaimer">
                    <em>
                        Note: This is an educational estimate. Actual solar generation may vary based on
                        panel orientation, shading, system losses, and local weather conditions.
                    </em>
                </p>
            </div>
        </section>
    );
}

export default ResultsSection;
